name: Build and Push to GHCR

on:
  push:
    branches:
      - main
      - develop

env:
  MAJOR_MINOR: "1.0"

jobs:
  build:
    runs-on: ubuntu-latest
    
    # La "matrix" permet de ne pas répéter le code 3 fois. 
    # GitHub va lancer 3 jobs en parallèle pour tout ce qui est app
    strategy:
      matrix:
        app: [catalog, booking, worker]
    
    # Autorisations nécessaires pour pousser sur le registre et trivy
    permissions:
      contents: read
      packages: write
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # Token généré automatiquement par GitHub

      - name: Downcase GitHub username
        # Docker refuse les majuscules dans les noms d'images. 
        run: echo "REPO_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> ${GITHUB_ENV}

      - name: Build and push ${{ matrix.app }}
        uses: docker/build-push-action@v5
        with:
          context: ./apps/${{ matrix.app }}
          push: true
          tags: |
            ghcr.io/${{ env.REPO_OWNER }}/${{ matrix.app }}:latest
            ghcr.io/${{ env.REPO_OWNER }}/${{ matrix.app }}:v${{ env.MAJOR_MINOR }}.${{ github.run_number }}

      - name: Trivy scan for ${{ matrix.app }}
        uses: aquasecurity/trivy-action@master
        with:
          # On cible l'image qu'on vient juste de construire
          image-ref: ghcr.io/${{ env.REPO_OWNER }}/${{ matrix.app }}:v${{ env.MAJOR_MINOR }}.${{ github.run_number }}
          severity: HIGH,CRITICAL
          exit-code: '1' # ⚠️ obligatoire pour bloquer la pipeline

      - name: Bump tag in gitops repo
        run: |
          # 1. Clone le dépôt GitOps
          git clone https://x-access-token:${{ secrets.GITOPS_PAT }}@github.com/${{ env.REPO_OWNER }}/micro-trips-gitops.git
          cd micro-trips-gitops
          
          # 2. Configure l'identité du robot
          git config user.email "ci@bot.github.com"
          git config user.name "GitHub Actions CI"
          
          # 3. Détecte automatiquement si l'app utilise un Rollout ou un Deployment
          if [ -f "manifests/business/${{ matrix.app }}/rollout.yaml" ]; then
            MANIFEST_PATH="manifests/business/${{ matrix.app }}/rollout.yaml"
          elif [ -f "manifests/business/${{ matrix.app }}/deployment.yaml" ]; then
            MANIFEST_PATH="manifests/business/${{ matrix.app }}/deployment.yaml"
          else
            echo "Erreur : Aucun fichier rollout.yaml ou deployment.yaml trouvé pour ${{ matrix.app }}"
            exit 0
          fi
          
          # 4. Modifie l'image avec le nouveau Tag
          VERSION="v${{ env.MAJOR_MINOR }}.${{ github.run_number }}"
          sed -i "s|image: .*${{ matrix.app }}:.*|image: ghcr.io/${{ env.REPO_OWNER }}/${{ matrix.app }}:${VERSION}|g" "$MANIFEST_PATH"

          # 5. Ajoute le fichier modifié
          git add "$MANIFEST_PATH"
          
          # 6. Commit
          git commit -m "chore(gitops): bump ${{ matrix.app }} to ${VERSION}" || echo "Aucun changement à commiter"
          
          # 7. Télécharge les derniers changements des autres robots juste avant de pousser au cas ou
          git pull --rebase origin main
          
          git push